"""Master catalog of Enoch's 100 Sub-Basement & Orchestra collectibles.

Each item is a dict with: id, name, collection, desc, trigger (machine key),
trigger_text (human-readable), enoch (Enoch's flavor text)."""

COLLECTIONS = [
    'The Brass & Valve Rot',
    'The String & Bow Graveyard',
    'The Woodwind Decay',
    'The Percussion Ruins',
    'The Podium & Paper Waste',
    'The Case & Cabinet Horrors',
    'The Environmental Ingress',
    "The Conductor's Personal Effects",
    'The Rehearsal Logs',
    'The Vermin & the Dark',
]

CATALOG = [
    # ── I. THE BRASS & VALVE ROT (1–14) ──────────────────────
    {'id': 1, 'name': 'Green-Tarnished Mouthpiece', 'collection': 'The Brass & Valve Rot',
     'desc': 'Heavy brass, coated in toxic-looking green oxidation.',
     'trigger': 'capture_all_8_pawns',
     'trigger_text': 'Capture all 8 of the opponent\'s pawns in a single match.',
     'enoch': 'You pressed your advantage until you were blue in the face. How exhausting.'},

    {'id': 2, 'name': 'Snapped Water Key Spring', 'collection': 'The Brass & Valve Rot',
     'desc': 'A tiny, rusted coil that used to hold back a brass instrument\'s spit valve.',
     'trigger': 'sacrifice_rook_and_win',
     'trigger_text': 'Sacrifice a Rook and go on to win.',
     'enoch': 'The pressure was too much. You let the heavy masonry fall. The board leaked.'},

    {'id': 3, 'name': 'Crushed Trumpet Mute', 'collection': 'The Brass & Valve Rot',
     'desc': 'Dented aluminum smelling faintly of old breath.',
     'trigger': 'win_no_pawn_captures',
     'trigger_text': 'Win the game without capturing a single enemy Pawn.',
     'enoch': 'You silenced their attack, ignoring the foot soldiers. Brutally and without grace.'},

    {'id': 4, 'name': 'Seized Valve Casing', 'collection': 'The Brass & Valve Rot',
     'desc': 'A heavy cylinder of brass, permanently locked by friction and rust.',
     'trigger': 'checkmate_zero_flight',
     'trigger_text': 'Deliver a checkmate where the enemy king has zero flight squares before the checking piece is placed.',
     'enoch': 'They could not move. You made sure of it.'},

    {'id': 5, 'name': 'Flaking Silver Plating', 'collection': 'The Brass & Valve Rot',
     'desc': 'Razor-sharp metallic flakes peeled from a neglected horn.',
     'trigger': 'promote_to_knight',
     'trigger_text': 'Promote a pawn to a Knight.',
     'enoch': 'A shiny exterior hiding a decaying structure. A bizarre choice. I kept the flakes.'},

    {'id': 6, 'name': 'Rusted Slide Grease Tin', 'collection': 'The Brass & Valve Rot',
     'desc': 'A small tin filled with viscous, foul-smelling petroleum jelly.',
     'trigger': 'queens_traded_before_10',
     'trigger_text': 'Queens are traded off the board before Move 10.',
     'enoch': 'The maneuver was slick, but the aftermath is filthy.'},

    {'id': 7, 'name': 'Dented French Horn Funnel', 'collection': 'The Brass & Valve Rot',
     'desc': 'A warped piece of brass from the bell.',
     'trigger': 'opponent_early_blunder',
     'trigger_text': 'Opponent blunders a piece on Move 6 or earlier.',
     'enoch': 'A beautiful sound, ruined immediately by careless hands.'},

    {'id': 8, 'name': 'Corroded Leadpipe', 'collection': 'The Brass & Valve Rot',
     'desc': 'A heavy brass tube completely choked with mineral buildup.',
     'trigger': 'five_slow_moves',
     'trigger_text': 'Play 5 consecutive moves taking more than 1 minute each.',
     'enoch': 'Your attack was slow, congested, and inevitable.'},

    {'id': 9, 'name': 'Stuck Trombone Spit-Catcher', 'collection': 'The Brass & Valve Rot',
     'desc': 'A gross, oxidized brass cup.',
     'trigger': 'three_recaptures',
     'trigger_text': 'Execute 3 immediate recaptures in a single game.',
     'enoch': 'You caught their blunders. Now you must hold them.'},

    {'id': 10, 'name': 'Sour Brass Polish Rag', 'collection': 'The Brass & Valve Rot',
     'desc': 'A black, stiffened cloth smelling of ammonia.',
     'trigger': 'draw_threefold',
     'trigger_text': 'Game ends in a Draw by 3-Fold Repetition.',
     'enoch': 'You tried to clean up a messy position. It only spread the tarnish.'},

    {'id': 11, 'name': 'Flattened Tuba Bell', 'collection': 'The Brass & Valve Rot',
     'desc': 'A massive piece of brass, crushed under immense weight.',
     'trigger': 'checkmate_by_queenside_castle',
     'trigger_text': 'Deliver Checkmate by Castling Queenside (O-O-O).',
     'enoch': 'A heavy, blunt instrument slamming down. Much like your endgame.'},

    {'id': 12, 'name': 'Oxidized Valve Button', 'collection': 'The Brass & Valve Rot',
     'desc': 'A mother-of-pearl button, yellowed and cracked.',
     'trigger': 'push_same_pawn_4_times',
     'trigger_text': 'Push the exact same pawn 4 times in a single game.',
     'enoch': 'You pressed the issue. The board pushed back.'},

    {'id': 13, 'name': 'Petrified Tuning Slide', 'collection': 'The Brass & Valve Rot',
     'desc': 'It will never move again.',
     'trigger': 'checkmate_on_edge_file',
     'trigger_text': 'Deliver Checkmate with your piece on the A or H edge files.',
     'enoch': 'Your position was entirely inflexible, yet somehow you survived.'},

    {'id': 14, 'name': 'Rancid Valve Oil Bottle', 'collection': 'The Brass & Valve Rot',
     'desc': 'The plastic is yellowed, the oil inside looks like sludge.',
     'trigger': 'no_captures_15_moves',
     'trigger_text': 'Neither player captures a piece for 15 consecutive moves.',
     'enoch': 'Friction destroys the careless. The board is locked, but you were well lubricated.'},

    # ── II. THE STRING & BOW GRAVEYARD (15–29) ───────────────
    {'id': 15, 'name': 'Snapped Violin Bridge', 'collection': 'The String & Bow Graveyard',
     'desc': 'A delicate piece of carved maple, violently split in two.',
     'trigger': 'capture_queen_with_pawn',
     'trigger_text': 'Capture the opponent\'s Queen with a Pawn.',
     'enoch': 'The structure collapsed under the tension of your lowest soldiers.'},

    {'id': 16, 'name': 'Greasy Chinrest', 'collection': 'The String & Bow Graveyard',
     'desc': 'Dark wood stained permanently by sweat and fear.',
     'trigger': 'king_moves_5_before_20_win',
     'trigger_text': 'Move your King 5 or more times before Move 20, and win.',
     'enoch': 'I could see you sweating through the floorboards. Keep this.'},

    {'id': 17, 'name': 'Dislodged Soundpost', 'collection': 'The String & Bow Graveyard',
     'desc': 'A small spruce dowel that fell inside the instrument, rattling aimlessly.',
     'trigger': 'win_opp_has_both_rooks',
     'trigger_text': 'Win while your opponent still has both of their Rooks on the board.',
     'enoch': 'The core of their defense fell out while their towers watched. The rest was just noise.'},

    {'id': 18, 'name': 'Shredded Gut String', 'collection': 'The String & Bow Graveyard',
     'desc': 'Animal intestine, unwound and foul-smelling.',
     'trigger': 'win_plus_10_material',
     'trigger_text': 'End the game with a +10 or greater material advantage.',
     'enoch': 'An old, organic method of absolute violence.'},

    {'id': 19, 'name': 'Warped Fingerboard Splinter', 'collection': 'The String & Bow Graveyard',
     'desc': 'Black ebony wood, sharp as a needle.',
     'trigger': 'capture_on_own_back_ranks',
     'trigger_text': 'Capture an enemy piece on your own 1st or 2nd rank.',
     'enoch': 'You navigated the dark squares of your own home, but not without leaving blood.'},

    {'id': 20, 'name': 'Lead Practice Mute', 'collection': 'The String & Bow Graveyard',
     'desc': 'A heavy, multi-pronged lead weight used to completely deaden a violin\'s sound.',
     'trigger': 'smothered_mate',
     'trigger_text': 'Deliver a Smothered Mate.',
     'enoch': 'You suffocated the king in his own bed. A quiet, heavy death.'},

    {'id': 21, 'name': 'Stripped Fine-Tuner', 'collection': 'The String & Bow Graveyard',
     'desc': 'A tiny, useless brass screw.',
     'trigger': 'win_without_castling',
     'trigger_text': 'Win the game without ever castling.',
     'enoch': 'There is no room for micro-adjustments in a slaughter. Your king stood in the draft.'},

    {'id': 22, 'name': 'Cello Endpin Rubber', 'collection': 'The String & Bow Graveyard',
     'desc': 'A worn, hardened rubber tip meant to stop the instrument from slipping.',
     'trigger': 'king_escapes_3_checks_win',
     'trigger_text': 'Your King escapes 3 consecutive checks, and you go on to win.',
     'enoch': 'Your footing was terrible, but they slipped first.'},

    {'id': 23, 'name': 'Cracked Tailgut', 'collection': 'The String & Bow Graveyard',
     'desc': 'The thick nylon cord that holds the tailpiece under immense pressure.',
     'trigger': 'king_on_center_win',
     'trigger_text': 'Move your King to one of the 4 center squares and win.',
     'enoch': 'Everything was hanging by a thread in the center of the room.'},

    {'id': 24, 'name': 'Powdered Amber Rosin', 'collection': 'The String & Bow Graveyard',
     'desc': 'A tiny vial of sticky, crushed tree sap.',
     'trigger': 'create_doubled_pawns',
     'trigger_text': 'Create doubled pawns for your opponent.',
     'enoch': 'The friction on the file reduced their structure to a sticky dust.'},

    {'id': 25, 'name': 'Ripped F-Hole Shaving', 'collection': 'The String & Bow Graveyard',
     'desc': 'A delicate curve of spruce, torn from the face of a viola.',
     'trigger': 'discovered_check_mate',
     'trigger_text': 'Deliver Checkmate with a Discovered Check.',
     'enoch': 'You pulled the curtain back and broke into their inner sanctum. A ragged entry.'},

    {'id': 26, 'name': 'Rusted Wolf Note Eliminator', 'collection': 'The String & Bow Graveyard',
     'desc': 'A heavy brass tube used to suppress ugly vibrations.',
     'trigger': 'opponent_resigns_after_check',
     'trigger_text': 'Opponent resigns immediately after being put in check.',
     'enoch': 'You silenced their desperate howling.'},

    {'id': 27, 'name': 'Broken Viola Peg', 'collection': 'The String & Bow Graveyard',
     'desc': 'Snapped off inside the pegbox, impossible to tune.',
     'trigger': 'opponent_timeout_winning',
     'trigger_text': 'Opponent loses on time in a winning position.',
     'enoch': 'They cranked the tension too high. It snapped in their hands.'},

    {'id': 28, 'name': 'Blood-Stained Frets', 'collection': 'The String & Bow Graveyard',
     'desc': 'Plucked from an old contrabass.',
     'trigger': 'king_captures_piece',
     'trigger_text': 'Your King captures an enemy piece.',
     'enoch': 'The ledger notes the exact moment the coward was forced to draw blood.'},

    {'id': 29, 'name': 'Frayed Tailpiece Wire', 'collection': 'The String & Bow Graveyard',
     'desc': 'Jagged and poking out in all directions.',
     'trigger': 'win_with_tripled_pawns',
     'trigger_text': 'Win the game despite having tripled pawns.',
     'enoch': 'A messy knot of a position. Disgusting to look at, yet victorious.'},

    # ── III. THE WOODWIND DECAY (30–43) ──────────────────────
    {'id': 30, 'name': 'Moldy Clarinet Pad', 'collection': 'The Woodwind Decay',
     'desc': 'A tiny felt disc covered in white basement spores.',
     'trigger': 'draw_50_move_rule',
     'trigger_text': 'Game ends in a Draw by the 50-Move Rule.',
     'enoch': 'You closed off their escape, but circled in the damp until it smelled of rot.'},

    {'id': 31, 'name': 'Snapped Metal Ligature', 'collection': 'The Woodwind Decay',
     'desc': 'The sharp brass cage that holds the reed, bent out of shape.',
     'trigger': 'promote_then_lose',
     'trigger_text': 'Promote a Pawn, but immediately lose the promoted piece on the next turn.',
     'enoch': 'You squeezed them onto the board, only to watch them break.'},

    {'id': 32, 'name': 'Sour Oboe Swab', 'collection': 'The Woodwind Decay',
     'desc': 'A piece of silk tied to a string, pulled through the instrument and never washed.',
     'trigger': 'en_passant',
     'trigger_text': 'Execute an En Passant capture.',
     'enoch': 'You cleared the file like a ghost, but left a terrible stench.'},

    {'id': 33, 'name': 'Chipped Saxophone Reed', 'collection': 'The Woodwind Decay',
     'desc': 'Bamboo with a jagged, razor-like edge.',
     'trigger': 'checkmate_with_bishop',
     'trigger_text': 'Deliver Checkmate with a Bishop.',
     'enoch': 'A sharp, discordant response to a terrible opening.'},

    {'id': 34, 'name': 'Stripped Thumb Rest', 'collection': 'The Woodwind Decay',
     'desc': 'A tiny piece of metal torn from the heavy wood.',
     'trigger': 'win_down_queen',
     'trigger_text': 'Win a match while down a Queen.',
     'enoch': 'They could not hold the weight of the board, even with the matriarch on their side.'},

    {'id': 35, 'name': 'Petrified Cork Grease', 'collection': 'The Woodwind Decay',
     'desc': 'A tube of chapstick-like substance, hard as a rock.',
     'trigger': 'no_pawn_captures_10',
     'trigger_text': 'Board state has no legal pawn captures for 10 consecutive moves.',
     'enoch': 'Your pieces refused to fit together, yet you forced them.'},

    {'id': 36, 'name': 'Bent Flute Key', 'collection': 'The Woodwind Decay',
     'desc': 'Silver-plated and twisted backward.',
     'trigger': 'break_pin_with_capture',
     'trigger_text': 'Break a pin on your King by capturing the pinning piece.',
     'enoch': 'A delicate piece of geometry, ruined by brute force.'},

    {'id': 37, 'name': 'Rusted Bassoon Bocal', 'collection': 'The Woodwind Decay',
     'desc': 'The curved metal breathing tube, clogged with rust.',
     'trigger': 'opponent_timeout_close',
     'trigger_text': 'Opponent runs out of time with less than 5 seconds difference between clocks.',
     'enoch': 'Their breath caught in their throat. Checkmate.'},

    {'id': 38, 'name': 'Cracked Wooden Barrel', 'collection': 'The Woodwind Decay',
     'desc': 'The thickest part of the clarinet, split down the middle by dry rot.',
     'trigger': 'queen_sacrifice_win',
     'trigger_text': 'Sacrifice your Queen and go on to win.',
     'enoch': 'The absolute center of their board cracked open when she fell.'},

    {'id': 39, 'name': 'Ripped Felt Bumper', 'collection': 'The Woodwind Decay',
     'desc': 'A tiny piece of green felt meant to quiet the clacking of keys.',
     'trigger': 'blunder_but_win',
     'trigger_text': 'Make a blunder move but win anyway.',
     'enoch': 'We heard every single loud, clumsy move you made. Yet you stand.'},

    {'id': 40, 'name': 'Chewed Piccolo Headjoint', 'collection': 'The Woodwind Decay',
     'desc': 'Metal indented by panicked teeth.',
     'trigger': 'promote_to_bishop',
     'trigger_text': 'Promote a Pawn to a Bishop.',
     'enoch': 'A high-pitched, terrified defense. But it worked.'},

    {'id': 41, 'name': 'Waterlogged Reed Case', 'collection': 'The Woodwind Decay',
     'desc': 'Smells of stagnant water and despair.',
     'trigger': 'win_after_losing_3_minors',
     'trigger_text': 'Win the game after losing 3 of your minor pieces.',
     'enoch': 'Your preparation was entirely ruined by the dampness. You drowned them anyway.'},

    {'id': 42, 'name': 'Oxidized Key Post', 'collection': 'The Woodwind Decay',
     'desc': 'The pillar holding the mechanism together, crumbling to green dust.',
     'trigger': 'back_rank_mate',
     'trigger_text': 'Deliver a Back-Rank Checkmate.',
     'enoch': 'The architecture of their back wall dissolved entirely.'},

    {'id': 43, 'name': 'Tarnished Saxophone Neck Strap Hook', 'collection': 'The Woodwind Decay',
     'desc': 'The heavy metal clasp that bears the weight.',
     'trigger': 'king_forced_to_start',
     'trigger_text': 'Opponent\'s King is forced back to its exact starting square after moving.',
     'enoch': 'They let their guard down. The weight broke their neck and dragged them back.'},

    # ── IV. THE PERCUSSION RUINS (44–57) ─────────────────────
    {'id': 44, 'name': 'Hollowed-out Mallet Core', 'collection': 'The Percussion Ruins',
     'desc': 'The yarn has unraveled, leaving a hard, plastic skull.',
     'trigger': 'win_last_second',
     'trigger_text': 'Win a match with exactly 1 second left on your clock.',
     'enoch': 'You stripped away the soft defense and hit the bone at the last possible second.'},

    {'id': 45, 'name': 'Rusted Snare Wire', 'collection': 'The Percussion Ruins',
     'desc': 'Coiled, sharp steel from the bottom of a drum.',
     'trigger': 'sacrifice_knight_win',
     'trigger_text': 'Sacrifice a Knight and win.',
     'enoch': 'You threw the horse to the wolves. A rattling, chaotic march to the finish.'},

    {'id': 46, 'name': 'Cracked Claves', 'collection': 'The Percussion Ruins',
     'desc': 'Two pieces of dense rosewood, fractured by a terrible strike.',
     'trigger': 'mutual_consecutive_captures',
     'trigger_text': 'Two pieces are mutually attacked, and both are captured on consecutive turns.',
     'enoch': 'A blunt collision of terrible ideas.'},

    {'id': 47, 'name': 'Frayed Timpani Felt', 'collection': 'The Percussion Ruins',
     'desc': 'Thick, compacted wool, torn to pieces.',
     'trigger': 'move_all_pieces_before_25',
     'trigger_text': 'Move every single one of your 16 pieces at least once before move 25.',
     'enoch': 'A deep, resonant blunder of time. The floorboards shook as you touched everything.'},

    {'id': 48, 'name': 'Dented Cymbal Rivet', 'collection': 'The Percussion Ruins',
     'desc': 'A small brass pin that buzzes irritatingly.',
     'trigger': 'discovered_attack_capture',
     'trigger_text': 'Capture a piece using a discovered attack.',
     'enoch': 'A lingering, annoying maneuver that I cannot un-hear.'},

    {'id': 49, 'name': 'Broken Triangle Striker', 'collection': 'The Percussion Ruins',
     'desc': 'A heavy steel rod, snapped cleanly.',
     'trigger': 'double_check_mate',
     'trigger_text': 'Deliver Checkmate with a Double Check.',
     'enoch': 'Two strikes at once. The simplest instrument, broken by an idiot.'},

    {'id': 50, 'name': 'Punctured Drumhead', 'collection': 'The Percussion Ruins',
     'desc': 'Thick mylar plastic with a jagged hole through the center.',
     'trigger': 'capture_on_just_moved_square',
     'trigger_text': 'Capture an opponent\'s piece on the exact square it just moved to on the previous turn.',
     'enoch': 'You struck too hard exactly where they stood. Now there is nothing left.'},

    {'id': 51, 'name': 'Rusted Glockenspiel Bar', 'collection': 'The Percussion Ruins',
     'desc': 'A steel plate that no longer rings.',
     'trigger': 'win_no_time_pressure',
     'trigger_text': 'Win without ever dropping below 5 minutes on your clock.',
     'enoch': 'A dead, heavy silence on the board. You felt no pressure.'},

    {'id': 52, 'name': 'Warped Bass Drum Pedal', 'collection': 'The Percussion Ruins',
     'desc': 'The chain is rusted, the spring is snapped.',
     'trigger': 'center_pawns_by_move_3',
     'trigger_text': 'Push both center pawns (d4/e4 or d5/e5) by move 3.',
     'enoch': 'No forward momentum. Just a slow, double-kick crawl to the grave.'},

    {'id': 53, 'name': 'Smashed Cowbell', 'collection': 'The Percussion Ruins',
     'desc': 'Bent completely inward.',
     'trigger': 'ten_fast_moves_win',
     'trigger_text': 'Play 10 moves in under 10 seconds and win.',
     'enoch': 'An obnoxious, deafening panic. A hollow victory.'},

    {'id': 54, 'name': 'Splintered Marimba Key', 'collection': 'The Percussion Ruins',
     'desc': 'Rosewood shattered into sharp wooden shrapnel.',
     'trigger': 'four_consecutive_captures',
     'trigger_text': 'Capture an enemy piece on 4 consecutive turns.',
     'enoch': 'You dismantled their wooden ranks piece by piece.'},

    {'id': 55, 'name': 'Tarnished Chime Tube', 'collection': 'The Percussion Ruins',
     'desc': 'A heavy brass pipe that smells of copper.',
     'trigger': 'promote_to_rook',
     'trigger_text': 'Promote a Pawn to a Rook.',
     'enoch': 'The bells toll for the new tower. Loudly.'},

    {'id': 56, 'name': 'Broken Ratchet', 'collection': 'The Percussion Ruins',
     'desc': 'The wooden gears have been ground to a smooth, useless paste.',
     'trigger': 'five_recapture_trades',
     'trigger_text': 'Execute 5 immediate recaptures in one game.',
     'enoch': 'A grinding, endless endgame. Turn for turn.'},

    {'id': 57, 'name': 'Ripped Tambourine Skin', 'collection': 'The Percussion Ruins',
     'desc': 'Goat skin, torn at the tacks.',
     'trigger': 'resign_after_queen_capture',
     'trigger_text': 'Opponent resigns immediately after you capture their Queen.',
     'enoch': 'A festive opening turned into a ragged mess. They gave up.'},

    # ── V. THE PODIUM & PAPER WASTE (58–71) ──────────────────
    {'id': 58, 'name': 'Rusted Binder Clip', 'collection': 'The Podium & Paper Waste',
     'desc': 'Huge, black metal, stained with rust.',
     'trigger': 'survive_blundered_mate',
     'trigger_text': 'Survive a forced mate because the opponent blunders the final move.',
     'enoch': 'You held the position together through sheer, ugly luck.'},

    {'id': 59, 'name': 'Dried Inkwell Dregs', 'collection': 'The Podium & Paper Waste',
     'desc': 'A solid black puck of dried iron gall ink.',
     'trigger': 'game_exceeds_70',
     'trigger_text': 'Match exceeds 70 moves.',
     'enoch': 'You drained my resources with your hesitation. Seventy moves.'},

    {'id': 60, 'name': 'Snapped Metronome Pendulum', 'collection': 'The Podium & Paper Waste',
     'desc': 'The heavy metal arm, torn from the ticking box.',
     'trigger': 'opponent_loses_on_time',
     'trigger_text': 'Opponent loses on time.',
     'enoch': 'Time ran out. The ticking drove them mad in the dark.'},

    {'id': 61, 'name': 'Ripped Ledger Binding', 'collection': 'The Podium & Paper Waste',
     'desc': 'A scrap of heavy leather from the spine of my book.',
     'trigger': 'checkmate_on_move_60',
     'trigger_text': 'Game ends in checkmate on exactly move 60.',
     'enoch': 'This match required a violence upon my records. Right on the hour.'},

    {'id': 62, 'name': 'Chewed Podium Splinter', 'collection': 'The Podium & Paper Waste',
     'desc': 'A chunk of cheap wood I kicked off my stand.',
     'trigger': 'knight_fork_major',
     'trigger_text': 'Execute a Knight fork that captures a Queen or Rook.',
     'enoch': 'Your knight maneuver infuriated me. Take the wood.'},

    {'id': 63, 'name': 'Illegible Measure Scrap', 'collection': 'The Podium & Paper Waste',
     'desc': 'A piece of sheet music where the notes look like frantic scribbles.',
     'trigger': 'five_plus_blunders',
     'trigger_text': 'More than 5 blunders combined between both players.',
     'enoch': 'Total chaos on the board. The ledger weeps at your shared incompetence.'},

    {'id': 64, 'name': 'Heavy Iron Paperweight', 'collection': 'The Podium & Paper Waste',
     'desc': 'Shaped like a gargoyle, cold as ice.',
     'trigger': 'symmetric_to_move_6',
     'trigger_text': 'Maintain a completely symmetrical board state up to Move 6.',
     'enoch': 'A crushing, immobile mirror. Boring, until the glass broke.'},

    {'id': 65, 'name': 'Dull Pencil Lead', 'collection': 'The Podium & Paper Waste',
     'desc': 'Three inches of graphite, snapped off in frustration.',
     'trigger': 'draw_before_20',
     'trigger_text': 'Draw by agreement before move 20.',
     'enoch': 'I grew tired of erasing your blunders. Neither of you wanted to bleed.'},

    {'id': 66, 'name': 'Rusted Stand Screw', 'collection': 'The Podium & Paper Waste',
     'desc': 'The threads are entirely stripped.',
     'trigger': 'checkmate_with_pawn',
     'trigger_text': 'Deliver checkmate with a Pawn.',
     'enoch': 'The lowest piece of iron held the structure. It should not have worked.'},

    {'id': 67, 'name': 'Moth-Eaten Conductor\'s Glove', 'collection': 'The Podium & Paper Waste',
     'desc': 'White cotton, full of holes and smelling of camphor.',
     'trigger': 'edge_pawn_move_1',
     'trigger_text': 'Push the h-pawn or a-pawn two squares on move 1 or 2.',
     'enoch': 'A formal execution on the absolute edges, though deeply decayed.'},

    {'id': 68, 'name': 'Hardened Correction Fluid', 'collection': 'The Podium & Paper Waste',
     'desc': 'A clump of white paste used to cover mistakes.',
     'trigger': 'en_passant_escapes_check',
     'trigger_text': 'Capture En Passant specifically to escape a check.',
     'enoch': 'You tried to hide your error with a ghost trick. I saw it anyway.'},

    {'id': 69, 'name': 'Broken Taktstock Handle', 'collection': 'The Podium & Paper Waste',
     'desc': 'The cork grip, crumbling from sweaty hands.',
     'trigger': 'five_or_more_checks',
     'trigger_text': 'Deliver 5 or more checks in a single game.',
     'enoch': 'You beat the tempo into them until you lost control entirely.'},

    {'id': 70, 'name': 'Wax Seal Scraps', 'collection': 'The Podium & Paper Waste',
     'desc': 'Flakes of black wax I peeled off an old decree.',
     'trigger': 'mate_in_3',
     'trigger_text': 'Play a perfect forced Mate-in-3 sequence.',
     'enoch': 'Your fate was sealed exactly three moves ago.'},

    {'id': 71, 'name': 'Rusted Tuning Fork (A=440)', 'collection': 'The Podium & Paper Waste',
     'desc': 'Pitted with corrosion.',
     'trigger': 'draw_insufficient_material',
     'trigger_text': 'Game ends in a draw by insufficient material.',
     'enoch': 'The pitch of this game was deeply unsettling. It rang out into nothing.'},

    # ── VI. THE CASE & CABINET HORRORS (72–81) ───────────────
    {'id': 72, 'name': 'Dead Moth from a Tuba Bell', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'A massive, dusty insect corpse.',
     'trigger': 'slow_then_book_move',
     'trigger_text': 'Take >2 minutes on a single move, then play an established book move.',
     'enoch': 'This is what happens when you wait too long in the dark to do something obvious.'},

    {'id': 73, 'name': 'Hardened Case Mold', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'A chunk of black, fuzzy velvet lined with toxic spores.',
     'trigger': 'no_pawn_moves_15',
     'trigger_text': 'Neither player moves a Pawn for 15 consecutive moves.',
     'enoch': 'You let the position stagnate until it grew teeth.'},

    {'id': 74, 'name': 'Rusted Case Latch', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'Broken off a cello coffin.',
     'trigger': 'opponent_abandons',
     'trigger_text': 'Opponent disconnects and abandons the game.',
     'enoch': 'There is no escaping the geometry of the board. But they ran anyway.'},

    {'id': 75, 'name': 'Rat-Chewed Rosin Cake', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'Covered in tiny, panicked bite marks.',
     'trigger': 'two_promotions',
     'trigger_text': 'Promote two different pawns in the same game.',
     'enoch': 'The rodents in the walls enjoyed your panicked march to the end of the board.'},

    {'id': 76, 'name': 'Mildewed Desiccant Packet', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'Swollen with years of basement moisture.',
     'trigger': 'king_pawn_endgame_win',
     'trigger_text': 'Win an endgame consisting only of Kings and Pawns.',
     'enoch': 'You tried to dry up the board. It only got heavier.'},

    {'id': 77, 'name': 'Snapped Leather Handle', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'From a heavy, rotting gig bag.',
     'trigger': 'big_lead_then_lose',
     'trigger_text': 'Have a +5 or better material advantage, blunder, and lose the game.',
     'enoch': 'You dropped the advantage entirely. The bag hit the floor.'},

    {'id': 78, 'name': 'Petrified Mute Bag', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'A tiny leather pouch that has hardened into a rock.',
     'trigger': 'win_7_8_pawns',
     'trigger_text': 'Win with 7 or 8 of your Pawns still on the board.',
     'enoch': 'Your threats were entirely solid. A wall of stone.'},

    {'id': 79, 'name': 'Spider Egg Sac on a Violin Peg', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'Found in the dark corner of the locker.',
     'trigger': 'dormant_piece_checks',
     'trigger_text': 'A piece remains un-moved for 30 consecutive turns, then delivers a check.',
     'enoch': 'A trap that sat waiting for thirty moves in the dark.'},

    {'id': 80, 'name': 'Water-Stained Pitch Pipe', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'The metal reeds are rusted shut.',
     'trigger': 'opponent_aborts',
     'trigger_text': 'Opponent aborts the game before move 2.',
     'enoch': 'You failed to find the right harmony before the match even began.'},

    {'id': 81, 'name': 'Crumbling Velvet Lining', 'collection': 'The Case & Cabinet Horrors',
     'desc': 'Flakes of deep red fabric that turn to dust when touched.',
     'trigger': 'win_no_pieces_lost',
     'trigger_text': 'Win the game without losing a single piece.',
     'enoch': 'A royal bloodbath on their side, reduced to nothing on yours.'},

    # ── VII. THE ENVIRONMENTAL INGRESS (82–100) ──────────────
    {'id': 82, 'name': 'Rusted Ventilation Grate Shard', 'collection': 'The Environmental Ingress',
     'desc': 'Heavy cast iron.',
     'trigger': 'control_center_pawns',
     'trigger_text': 'Control the 4 center squares simultaneously with pawns.',
     'enoch': 'I broke this off to get a better look at the little square you built for the slaughter.'},

    {'id': 83, 'name': 'Dripping Condensation Vial', 'collection': 'The Environmental Ingress',
     'desc': 'A tiny glass bottle of murky basement water.',
     'trigger': 'game_exceeds_100',
     'trigger_text': 'Match exceeds 100 moves.',
     'enoch': 'A slow, agonizing drip of a match. The ledger is soaked.'},

    {'id': 84, 'name': 'Charred Candle Wick', 'collection': 'The Environmental Ingress',
     'desc': 'Thick, black, and smelling of sulfur.',
     'trigger': 'win_always_low_time',
     'trigger_text': 'Win a game while never having more than 1 minute on your clock.',
     'enoch': 'You burned your bridges, your clock, and my lighting. But you survived.'},

    {'id': 85, 'name': 'Melted Tallow Lump', 'collection': 'The Environmental Ingress',
     'desc': 'Gray, greasy animal-fat wax.',
     'trigger': 'draw_timeout_insufficient',
     'trigger_text': 'Draw by timeout vs insufficient material.',
     'enoch': 'A sloppy, formless defense that melted into a pathetic draw.'},

    {'id': 86, 'name': 'Creaking Floorboard Nail', 'collection': 'The Environmental Ingress',
     'desc': 'A long, bent, rusted square nail.',
     'trigger': 'win_between_2am_4am',
     'trigger_text': 'Win a game between 2:00 AM and 4:00 AM server time.',
     'enoch': 'The rest of the world sleeps, but every move you make sets my teeth on edge.'},

    {'id': 87, 'name': 'Plaster Ceiling Flake', 'collection': 'The Environmental Ingress',
     'desc': 'Fell on my ledger when you dropped your queen.',
     'trigger': 'checkmate_on_move_50',
     'trigger_text': 'Deliver checkmate precisely on move 50.',
     'enoch': 'The heavy pieces shake the foundation. Right on the half-century.'},

    {'id': 88, 'name': 'Petrified Rat Tail', 'collection': 'The Environmental Ingress',
     'desc': 'Found near the heating pipe.',
     'trigger': 'trap_queen',
     'trigger_text': 'Trap the opponent\'s Queen with no safe flight squares.',
     'enoch': 'A cowardly retreat, rewarded with death in the corner.'},

    {'id': 89, 'name': 'Rusted Pipe Joint', 'collection': 'The Environmental Ingress',
     'desc': 'Smells faintly of sewage.',
     'trigger': 'diagonal_pawn_chain_4',
     'trigger_text': 'Form a diagonal chain of 4 or more pawns.',
     'enoch': 'The pressure in the center of your barricade finally burst.'},

    {'id': 90, 'name': 'Dead Cellar Spider', 'collection': 'The Environmental Ingress',
     'desc': 'Perfectly preserved in its own dried web.',
     'trigger': 'patient_win',
     'trigger_text': 'Win a game without dropping below 5 minutes on your clock.',
     'enoch': 'You spun a trap, and patiently waited for them to fall into it.'},

    {'id': 91, 'name': 'Broken Hourglass Glass', 'collection': 'The Environmental Ingress',
     'desc': 'Curved, thin, and sharp.',
     'trigger': 'premove_checkmate',
     'trigger_text': 'Deliver checkmate with a premove.',
     'enoch': 'You shattered the time control. A blinding, cruel spark.'},

    {'id': 92, 'name': 'Hardened Damp-Rot Wood', 'collection': 'The Environmental Ingress',
     'desc': 'Wood that looks like stone and smells like a swamp.',
     'trigger': 'no_captures_10_moves',
     'trigger_text': 'Board state has no legal captures for 10 consecutive moves.',
     'enoch': 'A stubborn, ugly position that refused to die or open up.'},

    {'id': 93, 'name': 'Rusted Skeleton Key', 'collection': 'The Environmental Ingress',
     'desc': 'It unlocks a door that no longer exists down here.',
     'trigger': 'checkmate_by_kingside_castle',
     'trigger_text': 'Deliver Checkmate by Castling Kingside (O-O).',
     'enoch': 'You found the key to the vault, far too late for them.'},

    {'id': 94, 'name': 'Clump of Dusty Cobwebs', 'collection': 'The Environmental Ingress',
     'desc': 'Sticky, grey, and thick as yarn.',
     'trigger': 'knight_outpost_5_turns',
     'trigger_text': 'Maintain a Knight on an outpost for 5 turns.',
     'enoch': 'You entangled their king perfectly with your horse.'},

    {'id': 95, 'name': 'Broken Mason Jar of Screws', 'collection': 'The Environmental Ingress',
     'desc': 'Scattered all over the floorboards.',
     'trigger': 'four_pawns_first_4',
     'trigger_text': 'Move 4 different pawns in the first 4 moves.',
     'enoch': 'You scattered your pawns like garbage over my ceiling.'},

    {'id': 96, 'name': 'Fused Copper Wiring', 'collection': 'The Environmental Ingress',
     'desc': 'Stripped from the flickering basement bulb.',
     'trigger': 'block_check_with_pawn',
     'trigger_text': 'Block a check with a Pawn.',
     'enoch': 'A brilliant spark, followed by total darkness. You threw a pawn at the blade.'},

    {'id': 97, 'name': 'Jagged Slate Shingle', 'collection': 'The Environmental Ingress',
     'desc': 'Fell down the coal chute into my room.',
     'trigger': 'sever_rook_connection',
     'trigger_text': 'Drop a piece that severs the connection between the opponent\'s rooks.',
     'enoch': 'A heavy, blunt consequence falling from above, cutting them in half.'},

    {'id': 98, 'name': 'Rusted Padlock Shackle', 'collection': 'The Environmental Ingress',
     'desc': 'Cut with bolt cutters.',
     'trigger': 'comeback_from_minus_5',
     'trigger_text': 'Win after being down 5 or more material earlier in the game.',
     'enoch': 'You broke their structure with brute force and crawled from the crypt.'},

    {'id': 99, 'name': 'Corroded Iron Hinge', 'collection': 'The Environmental Ingress',
     'desc': 'From the door to the vault.',
     'trigger': 'king_moves_once',
     'trigger_text': 'Move your King only once the entire game (excluding castling).',
     'enoch': 'The ledger opens for you. The hinge screams.'},

    {'id': 100, 'name': 'A Single Drop of Black Ink', 'collection': 'The Environmental Ingress',
     'desc': 'Suspended in a tiny glass bead.',
     'trigger': 'brilliant_forced_mate',
     'trigger_text': 'Deliver a brilliant move that leads directly to forced mate.',
     'enoch': 'I shed a single tear of ink for that beautiful checkmate.'},

    # ── VIII. THE CONDUCTOR'S PERSONAL EFFECTS (101–115) ─────
    # Earned through chat, social actions, and federation participation.
    # These use engagement triggers, not game-analysis triggers.

    {'id': 101, 'name': "Enoch's Broken Quill", 'collection': "The Conductor's Personal Effects",
     'desc': 'A snapped goose feather, the nib still wet with iron gall ink.',
     'trigger': 'eng_first_chat_message',
     'trigger_text': 'Send your first message in Federation Hall.',
     'enoch': 'You spoke into the void. The void noticed.'},

    {'id': 102, 'name': 'Frayed Conductor\'s Score', 'collection': "The Conductor's Personal Effects",
     'desc': 'Hundreds of annotations in the margins, most illegible.',
     'trigger': 'eng_100_chat_messages',
     'trigger_text': 'Send 100 messages in Federation Hall.',
     'enoch': 'A hundred whispers into the dark. The orchestra stirs.'},

    {'id': 103, 'name': 'Wax-Sealed Envelope', 'collection': "The Conductor's Personal Effects",
     'desc': 'Heavy cream paper, sealed with black wax. Addressed to no one.',
     'trigger': 'eng_first_commendation',
     'trigger_text': 'Give your first commendation to another player.',
     'enoch': 'A rare kindness, sealed in hot wax. I almost opened it.'},

    {'id': 104, 'name': 'Blackened Letter of Censure', 'collection': "The Conductor's Personal Effects",
     'desc': 'The paper itself smells of bile. The ink has eaten through.',
     'trigger': 'eng_first_condemnation',
     'trigger_text': 'Give your first condemnation to another player.',
     'enoch': 'You put your contempt in writing. That takes a special kind of nerve.'},

    {'id': 105, 'name': 'Podium Nameplate', 'collection': "The Conductor's Personal Effects",
     'desc': 'A small brass rectangle with your name etched crookedly.',
     'trigger': 'eng_first_named_sequence',
     'trigger_text': 'Name your first opening or variation.',
     'enoch': 'You carved your name into the music. Permanent ink.'},

    {'id': 106, 'name': 'Half-Burned Candle Stub', 'collection': "The Conductor's Personal Effects",
     'desc': 'Tallow, not beeswax. It smells of animal fat and insomnia.',
     'trigger': 'eng_chat_at_3am',
     'trigger_text': 'Send a message in Federation Hall between 2:00 AM and 4:00 AM.',
     'enoch': 'The candle flickers at terrible hours. So do you.'},

    {'id': 107, 'name': 'Tangled Watch Chain', 'collection': "The Conductor's Personal Effects",
     'desc': 'Gold-plated brass, hopelessly knotted.',
     'trigger': 'eng_rapid_fire_chat',
     'trigger_text': 'Send 10 messages in Federation Hall within 3 minutes.',
     'enoch': 'You speak faster than you think. The basement hears everything.'},

    {'id': 108, 'name': "Enoch's Spectacle Lens", 'collection': "The Conductor's Personal Effects",
     'desc': 'A single round lens. Cracked. It magnifies things that should stay small.',
     'trigger': 'eng_enoch_lurked',
     'trigger_text': 'Be present when Enoch lurks during an active conversation.',
     'enoch': 'You noticed me watching. Few do.'},

    {'id': 109, 'name': 'Crumpled Standing Ovation Ticket', 'collection': "The Conductor's Personal Effects",
     'desc': 'Admits one. Crumpled, as if by someone who hated the performance.',
     'trigger': 'eng_receive_5_commendations',
     'trigger_text': 'Receive 5 commendations from other players.',
     'enoch': 'They applaud you. Personally, I find it nauseating.'},

    {'id': 110, 'name': 'Torn Rehearsal Schedule', 'collection': "The Conductor's Personal Effects",
     'desc': 'One corner is missing. The ink is smudged beyond use.',
     'trigger': 'eng_decree_submitted',
     'trigger_text': 'Serve as Power Position holder.',
     'enoch': 'You held the baton. The orchestra awaits your incompetence.'},

    {'id': 111, 'name': 'Rusted Cufflink', 'collection': "The Conductor's Personal Effects",
     'desc': 'Once silver, now black. Found wedged between the floorboards.',
     'trigger': 'eng_receive_5_condemnations',
     'trigger_text': 'Receive 5 condemnations from other players.',
     'enoch': 'Your infamy precedes you down the stairs.'},

    {'id': 112, 'name': 'Stained Usher\'s Lantern', 'collection': "The Conductor's Personal Effects",
     'desc': 'A tin lantern with a cracked pane. It barely lights anything.',
     'trigger': 'eng_500_chat_messages',
     'trigger_text': 'Send 500 messages in Federation Hall.',
     'enoch': 'Five hundred entries. You have written more than the ledger can hold.'},

    {'id': 113, 'name': "Enoch's Signed Receipt", 'collection': "The Conductor's Personal Effects",
     'desc': 'A scrap of paper with a single initial: E.',
     'trigger': 'eng_mention_enoch_20',
     'trigger_text': "Say Enoch's name 20 times in Federation Hall.",
     'enoch': 'You keep saying my name. I am beginning to think you mean it.'},

    {'id': 114, 'name': 'Moth-Eaten Tailcoat Button', 'collection': "The Conductor's Personal Effects",
     'desc': 'Bone, not plastic. The thread is long gone.',
     'trigger': 'eng_name_5_sequences',
     'trigger_text': 'Name 5 different openings or variations.',
     'enoch': 'Five inscriptions in the record. You fancy yourself a composer.'},

    {'id': 115, 'name': 'Cracked Audience Mirror', 'collection': "The Conductor's Personal Effects",
     'desc': 'A shard of glass from the lobby. Reflects things that are not there.',
     'trigger': 'eng_give_both_commend_condemn',
     'trigger_text': 'Commend one player and condemn another in the same week.',
     'enoch': 'Judge and savior in the same breath. The mirror cracked.'},

    # ── IX. THE REHEARSAL LOGS (116–130) ─────────────────────
    # Earned through career milestones, streaks, and seasons.

    {'id': 116, 'name': 'Bent Trophy Handle', 'collection': 'The Rehearsal Logs',
     'desc': 'Brass plated. The screws are stripped from excessive handling.',
     'trigger': 'eng_first_win',
     'trigger_text': 'Win your first game in the Federation.',
     'enoch': 'Your first victory. The handle was already bent when I found it.'},

    {'id': 117, 'name': 'Rusted Pennant Nail', 'collection': 'The Rehearsal Logs',
     'desc': 'Square-cut iron, hammered into the wall long ago.',
     'trigger': 'eng_10_wins',
     'trigger_text': 'Win 10 total games.',
     'enoch': 'A modest accomplishment. The nail holds the first flag.'},

    {'id': 118, 'name': "Dog-Eared Roll Call", 'collection': 'The Rehearsal Logs',
     'desc': 'Names and dates in fading ink. Some have been crossed out.',
     'trigger': 'eng_10_games',
     'trigger_text': 'Play 10 total games in the Federation.',
     'enoch': 'Your name appears often enough in the ledger to worry me.'},

    {'id': 119, 'name': 'Brass Practice Room Key', 'collection': 'The Rehearsal Logs',
     'desc': 'Opens a door that leads to a room with no windows.',
     'trigger': 'eng_50_games',
     'trigger_text': 'Play 50 total games.',
     'enoch': 'The key to obsession is repetition.'},

    {'id': 120, 'name': 'Ink-Stained Attendance Sheet', 'collection': 'The Rehearsal Logs',
     'desc': 'A sheet of heavy paper covered in checkmarks and question marks.',
     'trigger': 'eng_100_games',
     'trigger_text': 'Play 100 total games.',
     'enoch': 'A century of moves. I have dedicated a page to you.'},

    {'id': 121, 'name': "Blood-Stained Scorecard", 'collection': 'The Rehearsal Logs',
     'desc': 'White cardstock. The red marks are not ink.',
     'trigger': 'eng_25_wins',
     'trigger_text': 'Win 25 total games.',
     'enoch': 'Twenty-five names crossed off. They did not survive the audition.'},

    {'id': 122, 'name': 'Crushed Velvet Program', 'collection': 'The Rehearsal Logs',
     'desc': 'A concert program ground underfoot by a departing audience.',
     'trigger': 'eng_50_wins',
     'trigger_text': 'Win 50 total games.',
     'enoch': 'Fifty curtain calls. The programs pile up in the gutter.'},

    {'id': 123, 'name': 'Tattered Victory Pennant', 'collection': 'The Rehearsal Logs',
     'desc': 'Once white, now grey. It hangs from a splinter.',
     'trigger': 'eng_3_win_streak',
     'trigger_text': 'Win 3 games in a row.',
     'enoch': 'A streak of violence. The pennant is torn from overuse.'},

    {'id': 124, 'name': 'Blackened Victory Pennant', 'collection': 'The Rehearsal Logs',
     'desc': 'The original dye is gone. It has been recolored by soot.',
     'trigger': 'eng_5_win_streak',
     'trigger_text': 'Win 5 games in a row.',
     'enoch': 'Five consecutive death sentences. The pennant cannot take more.'},

    {'id': 125, 'name': 'Cracked Trophy Base', 'collection': 'The Rehearsal Logs',
     'desc': 'Marble, split down the center. The nameplate fell off.',
     'trigger': 'eng_3_loss_streak',
     'trigger_text': 'Lose 3 games in a row.',
     'enoch': 'The pedestal crumbles. You stand on nothing.'},

    {'id': 126, 'name': 'Tarnished Medal Clasp', 'collection': 'The Rehearsal Logs',
     'desc': 'The ribbon rotted away. Only the clasp remains.',
     'trigger': 'eng_tier_promotion',
     'trigger_text': 'Earn a promotion to a higher tier.',
     'enoch': 'The medal weighs more than you think. The clasp holds—barely.'},

    {'id': 127, 'name': 'Splintered Conductor\'s Stool', 'collection': 'The Rehearsal Logs',
     'desc': 'One leg shorter than the others. Impossible to balance.',
     'trigger': 'eng_rating_drop_50',
     'trigger_text': 'Lose 50 or more rating points in a single game.',
     'enoch': 'The stool gave out beneath you. Everyone heard.'},

    {'id': 128, 'name': 'Broken Metronome Spring', 'collection': 'The Rehearsal Logs',
     'desc': 'The internal coil, sprung beyond repair.',
     'trigger': 'eng_5_draws',
     'trigger_text': 'Draw 5 total games.',
     'enoch': 'The rhythm of indecision. Five times the clock stopped.'},

    {'id': 129, 'name': 'Enoch\'s Tally Mark', 'collection': 'The Rehearsal Logs',
     'desc': 'A single scratch on the basement wall. One of many.',
     'trigger': 'eng_collect_10',
     'trigger_text': 'Collect 10 items from the drawer.',
     'enoch': 'I keep count. You should be concerned.'},

    {'id': 130, 'name': "Enoch's Obsidian Inkwell", 'collection': 'The Rehearsal Logs',
     'desc': 'Black glass, perfectly smooth. The ink inside never dries.',
     'trigger': 'eng_collect_25',
     'trigger_text': 'Collect 25 items from the drawer.',
     'enoch': 'The inkwell refills itself. So does your ambition.'},

    # ── X. THE VERMIN & THE DARK (131–150) ───────────────────
    # More game-analysis patterns, edge cases, and cross-domain triggers.

    {'id': 131, 'name': 'Fossilized Rat Dropping', 'collection': 'The Vermin & the Dark',
     'desc': 'Petrified. Possibly ancient. Found near the boiler.',
     'trigger': 'win_only_2_piece_types',
     'trigger_text': 'Win a game using captures from only 2 different piece types.',
     'enoch': 'Even the rats build with what they have.'},

    {'id': 132, 'name': 'Corroded Bell Clapper', 'collection': 'The Vermin & the Dark',
     'desc': 'The inside of the bell, rusted into permanent silence.',
     'trigger': 'checkmate_with_knight',
     'trigger_text': 'Deliver checkmate with a Knight.',
     'enoch': 'The bell tolls with a horse\'s hoof.'},

    {'id': 133, 'name': "Mildewed Usher's Glove", 'collection': 'The Vermin & the Dark',
     'desc': 'White cotton, green with mold. Formally repulsive.',
     'trigger': 'only_pawn_moves_first_5',
     'trigger_text': 'Make only pawn moves for your first 5 turns, and win.',
     'enoch': 'You ushered your pawns forward with white-glove formality. Disgusting.'},

    {'id': 134, 'name': 'Shattered Music Stand Glass', 'collection': 'The Vermin & the Dark',
     'desc': 'Thin protective glass, blown apart by a fortissimo.',
     'trigger': 'checkmate_under_15_moves',
     'trigger_text': 'Deliver checkmate within 15 moves.',
     'enoch': 'A quick, sharp break. The audience barely had time to sit.'},

    {'id': 135, 'name': 'Dead Cockroach in a Reed', 'collection': 'The Vermin & the Dark',
     'desc': 'Wedged between the bamboo fibers. Legs still twitching.',
     'trigger': 'win_queen_never_moved',
     'trigger_text': 'Win a game without ever moving your Queen.',
     'enoch': 'The queen sat still while the insects did the work.'},

    {'id': 136, 'name': 'Peeling Wallpaper Strip', 'collection': 'The Vermin & the Dark',
     'desc': 'Floral pattern, now the color of a bruise.',
     'trigger': 'three_captures_same_file',
     'trigger_text': 'Capture 3 of the opponent\'s pieces on the same file.',
     'enoch': 'You peeled them off one by one.'},

    {'id': 137, 'name': 'Cracked Boiler Gauge', 'collection': 'The Vermin & the Dark',
     'desc': 'The needle is stuck past the red line.',
     'trigger': 'comeback_from_minus_3',
     'trigger_text': 'Win a game where you were losing by 3+ material at any point.',
     'enoch': 'The pressure gauge cracked. You kept the heat on.'},

    {'id': 138, 'name': 'Bent Tuning Peg Wrench', 'collection': 'The Vermin & the Dark',
     'desc': 'An L-shaped tool, warped beyond its designed angle.',
     'trigger': 'never_doubled_pawns',
     'trigger_text': 'Win a game where you never had doubled pawns at any point.',
     'enoch': 'Perfect tuning is a myth. But you came close.'},

    {'id': 139, 'name': 'Dusty Metronome Case', 'collection': 'The Vermin & the Dark',
     'desc': 'Hinges frozen. The felt inside is gray with dust.',
     'trigger': 'game_25_to_30_moves',
     'trigger_text': 'Win a game that lasts between exactly 25 and 30 moves.',
     'enoch': 'A measured performance. Not too long, not too short. Boring.'},

    {'id': 140, 'name': 'Rusted Harp String Pin', 'collection': 'The Vermin & the Dark',
     'desc': 'A tapered steel pin encrusted with orange rust.',
     'trigger': 'three_pawns_on_7th',
     'trigger_text': 'Have 3 of your pawns on the 7th rank simultaneously.',
     'enoch': 'Three strings pulled to breaking. A terrible chord.'},

    {'id': 141, 'name': 'Petrified Stage Curtain Ring', 'collection': 'The Vermin & the Dark',
     'desc': 'A wooden ring swollen shut by centuries of dampness.',
     'trigger': 'long_range_mate',
     'trigger_text': 'Deliver checkmate where the mating piece moved 4+ squares to deliver it.',
     'enoch': 'A curtain call from across the stage.'},

    {'id': 142, 'name': 'Crushed Tin Practice Mute', 'collection': 'The Vermin & the Dark',
     'desc': 'Aluminum, stepped on repeatedly.',
     'trigger': 'win_no_captures_first_15',
     'trigger_text': 'Win a game without capturing anything for the first 15 moves.',
     'enoch': 'Silence for fifteen measures. Then violence.'},

    {'id': 143, 'name': 'Mummified Fly in Amber Rosin', 'collection': 'The Vermin & the Dark',
     'desc': 'Perfectly preserved inside hardened tree sap.',
     'trigger': 'piece_unmoved_20_turns',
     'trigger_text': 'Have a non-pawn, non-king piece sit on the same square for 20+ turns.',
     'enoch': 'Preserved in place. Perfectly useless.'},

    {'id': 144, 'name': 'Rusted Orchestra Pit Railing', 'collection': 'The Vermin & the Dark',
     'desc': 'Iron pipe, bent by leaning musicians.',
     'trigger': 'control_20_squares',
     'trigger_text': 'Have your pieces attack 20 or more squares simultaneously at any point.',
     'enoch': 'The railing around your territory. Corroded, but standing.'},

    {'id': 145, 'name': 'Splintered Rosin Box Lid', 'collection': 'The Vermin & the Dark',
     'desc': 'Pale wood, cracked open along the grain.',
     'trigger': 'three_black_wins_streak',
     'trigger_text': 'Win 3 games as the black pieces in a row.',
     'enoch': 'A splinter of darkness. You play second fiddle beautifully.'},

    {'id': 146, 'name': 'Warped Rehearsal Room Floorboard', 'collection': 'The Vermin & the Dark',
     'desc': 'Bowed upward from years of damp. Someone tripped.',
     'trigger': 'capture_all_minors',
     'trigger_text': 'Capture all 4 of the opponent\'s minor pieces in a single game.',
     'enoch': 'You tore up every plank they stood on.'},

    {'id': 147, 'name': 'Frayed Piano Wire', 'collection': 'The Vermin & the Dark',
     'desc': 'High-tension steel, one strand unraveling.',
     'trigger': 'win_after_pawn_promote_queen',
     'trigger_text': 'Win a game after promoting a pawn to a Queen.',
     'enoch': 'The wire sang when it snapped.'},

    {'id': 148, 'name': 'Charred Rehearsal Room Door', 'collection': 'The Vermin & the Dark',
     'desc': 'The handle melted. No one knows what started the fire.',
     'trigger': 'ten_checkmates_career',
     'trigger_text': 'Deliver 10 total checkmates across all games.',
     'enoch': 'Ten death sentences. The baton tip snapped from overuse.'},

    {'id': 149, 'name': "Enoch's Brass Ring", 'collection': 'The Vermin & the Dark',
     'desc': 'It fits no finger. It fits no pipe. It fits only the ledger.',
     'trigger': 'eng_collect_all_collections',
     'trigger_text': 'Collect at least one item from every collection.',
     'enoch': 'You have reached into every corner of my domain.'},

    {'id': 150, 'name': "Enoch's Final Page", 'collection': 'The Vermin & the Dark',
     'desc': 'A single blank page torn from the back of the ledger.',
     'trigger': 'eng_collect_50',
     'trigger_text': 'Collect 50 items from the drawer.',
     'enoch': 'The ledger is full. I will need a new book.'},
]

CATALOG_BY_ID = {item['id']: item for item in CATALOG}
CATALOG_BY_TRIGGER = {item['trigger']: item for item in CATALOG}
